server:
  port: 8081
  servlet:
    path: /api
bmap: 
  enableCache: false
  interceptor: 
    include: /**
    exclude: /error,/**/*.*,/**/*swagger*/**,/token/**,/cache/**,/search/region/*
    


mybatis: 
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


logging:
#  level:
#    root: DEBUG
  config: classpath:logback-spring.xml
  
spring: 
  datasource:
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://39.104.77.201:3306/wxrobot?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
      url: jdbc:mysql://39.104.77.201:3306/wxrobot
      username: root
      password: 976225li
#      url: jdbc:mysql://bj-cdb-7o4y5cr2.sql.tencentcdb.com:62082/drch_screen_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
#      username: drch_screen
#      password: drch#screen_lp
#初始化大小
      initial-size: 1
#最小连接数
      min-idle: 1
#最大连接数
      max-active: 20
#获取连接等待超时时间
      max-wait: 60000
#间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
#一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
#测试语句是否执行正确
      validation-query: SELECT 'x'
#指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      test-while-idle: true
#借出连接时不要测试，否则很影响性能
      test-on-borrow: false
      test-on-return: false
#打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
#与Oracle数据库PSCache有关，再druid下可以设置的比较高
      max-pool-prepared-statement-per-connection-size: 20
#ES相关配置
  elasticsearch:
    jest:
      uris: http://192.168.0.26:9200,http://192.168.0.27:9200,http://192.168.0.28:9200
      multi-threaded: true
      read-timeout: 60000
      connection-timeout: 60000
