spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.104.77.201:3306/wxrobot
    username: root
    password: 976225li
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.drc.dataClean.model

server:
  port: 8081